PointOfInterest/Models/Rumah.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PointOfInterest.Models
{
    public class Rumah
    {
        [Key]
        [Required]
        public Guid Id { set; get; }
        [Required]
        public string Nama { set; get; }
        [Required]
        public string Type { set; get; }
        [Required]
        public string Alamat { set; get; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public DateTime Create { set; get; }
        public DateTime Update { set; get; }

        public Rumah()
        {
            Id = Guid.NewGuid();
            Create = DateTime.Now;
        }
    }
}

PointOfInterest/Controllers/RumahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PointOfInterest.Models;

namespace PointOfInterest.Controllers
{
    public class RumahController : Controller
    {
        private readonly Db _context;

        public RumahController()
        {
            _context = new Db();
        }

        // GET: Rumahs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rumah.ToListAsync());
        }

        // GET: Rumahs/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rumah = await _context.Rumah
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rumah == null)
            {
                return NotFound();
            }

            return View(rumah);
        }

        // GET: Rumahs/Rute/5
        public async Task<IActionResult> Rute(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rumah = await _context.Rumah
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rumah == null)
            {
                return NotFound();
            }

            return View(rumah);
        }

        // GET: Rumahs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rumahs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nama,Type,Alamat,Latitude,Longitude,Create,Update")] Rumah rumah)
        {
            if (ModelState.IsValid)
            {
                rumah.Id = Guid.NewGuid();
                _context.Add(rumah);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rumah);
        }

        // GET: Rumahs/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rumah = await _context.Rumah.FindAsync(id);
            if (rumah == null)
            {
                return NotFound();
            }
            return View(rumah);
        }

        // POST: Rumahs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nama,Type,Alamat,Latitude,Longitude,Create,Update")] Rumah rumah)
        {
            if (id != rumah.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    rumah.Update = DateTime.Now;
                    _context.Update(rumah);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RumahExists(rumah.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rumah);
        }

        // GET: Rumahs/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rumah = await _context.Rumah
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rumah == null)
            {
                return NotFound();
            }

            return View(rumah);
        }

        // POST: Rumahs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var rumah = await _context.Rumah.FindAsync(id);
            _context.Rumah.Remove(rumah);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RumahExists(Guid id)
        {
            return _context.Rumah.Any(e => e.Id == id);
        }

        public async Task<IActionResult> GetLocations()
        {
            var locations = new List<Locations>();
            var r = await _context.Rumah.ToListAsync();
            foreach(var each in r)
            {
                locations.Add(new Locations(double.Parse(each.Latitude), double.Parse(each.Longitude), each.Nama));
            }
            return Json(locations);
        }

        [Route("Rumah/HitungJarak/{Id}/{Lat}/{Long}")]
        public async Task<IActionResult> HitungJarak(Guid? id, double Lat, double Long)
        {
            if (id == null)
            {
                return NotFound();
            }
            var rumah = await _context.Rumah.FindAsync(id);
            Position pos1 = new Position
            {
                Latitude = double.Parse(rumah.Latitude),
                Longitude = double.Parse(rumah.Longitude)
            };
            Position pos2 = new Position
            {
                Latitude = Lat,//-6.914744;
                Longitude = Long//107.609810;
            };
            if (rumah == null)
            {
                return NotFound();
            }
            Haversine hv = new Haversine();
            double result = Math.Round(hv.Distance(pos1, pos2, DistanceType.Kilometers),2);
            return Json(result.ToString() + " KM");
        }
    }
}

PointOfInterest/Views/Rumah/Create.cshtml
@model PointOfInterest.Models.Rumah

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<hr />
<div class="row">
    <div class="col-lg-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="">Pilih Type</option>
                    <option value="36">36</option>
                    <option value="45">45</option>
                    <option value="72">72</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alamat" class="control-label"></label>
                <textarea asp-for="Alamat" class="form-control" rows="3" ></textarea>
                <span asp-validation-for="Alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Latitude" type="hidden" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group">
                <input asp-for="Longitude" type="hidden" class="form-control" readonly="readonly"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
    <div class="col-lg-6">
        <div id="myMap" style="position:relative; height:400px;"></div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type='text/javascript'>
        function LoadMap() {
            map = new Microsoft.Maps.Map('#myMap', {
                credentials: KeyAPI,
            });
            map.setView({
                mapTypeId: Microsoft.Maps.MapTypeId.road,
                center: new Microsoft.Maps.Location(-6.914744, 107.609810),
                zoom: 13
            });
            var center = map.getCenter();
            var Events = Microsoft.Maps.Events;
            var Location = Microsoft.Maps.Location;
            var Pushpin = Microsoft.Maps.Pushpin;
            var pins = [
                new Pushpin(new Location(center.latitude, center.longitude),
                    {
                        color: '#f00',
                        draggable: true,
                        icon: 'https://www.bingmapsportal.com/Content/images/poi_custom.png'
                    }),
            ];
            map.entities.push(pins);
            Events.addHandler(pins[0], 'dragend', function () {
                var pin_location = pins[0].getLocation();
                $("#Latitude").val(pin_location.latitude);
                $("#Longitude").val(pin_location.longitude);
                Microsoft.Maps.loadModule('Microsoft.Maps.Search', function () {
                    var searchManager = new Microsoft.Maps.Search.SearchManager(map);
                    var reverseGeocodeRequestOptions = {
                        location: new Microsoft.Maps.Location(pin_location.latitude, pin_location.longitude),
                        callback: function (answer, userData) {
                            //map.setView({ bounds: answer.bestView });
                            $("#Alamat").val(answer.address.formattedAddress);
                        }
                    };
                    searchManager.reverseGeocode(reverseGeocodeRequestOptions);
                });
            });
        }
    </script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PointOfInterest/Views/Rumah/Delete.cshtml
@model PointOfInterest.Models.Rumah

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alamat)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PointOfInterest/Views/Rumah/Details.cshtml
@model PointOfInterest.Models.Rumah

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alamat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Create)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Create)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Update)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Update)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PointOfInterest/Views/Rumah/Edit.cshtml
@model PointOfInterest.Models.Rumah

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<hr />
<div class="row">
    <div class="col-lg-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="">Pilih Type</option>
                    <option value="36">36</option>
                    <option value="45">45</option>
                    <option value="72">72</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alamat" class="control-label"></label>
                <textarea asp-for="Alamat" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Latitude" type="hidden" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Longitude" type="hidden" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
    <div class="col-lg-6">
        <div id="myMap" style="position:relative; height:400px;"></div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type='text/javascript'>
        var lat = $("#Latitude").val();
        var long = $("#Longitude").val();
        function LoadMap() {
            map = new Microsoft.Maps.Map('#myMap', {
                credentials: KeyAPI,
            });
            map.setView({
                mapTypeId: Microsoft.Maps.MapTypeId.road,
                center: new Microsoft.Maps.Location(lat, long),
                zoom: 13
            });
            var center = map.getCenter();
            var Events = Microsoft.Maps.Events;
            var Location = Microsoft.Maps.Location;
            var Pushpin = Microsoft.Maps.Pushpin;
            var pins = [
                new Pushpin(new Location(center.latitude, center.longitude),
                    {
                        color: '#f00',
                        draggable: true,
                        icon: 'https://www.bingmapsportal.com/Content/images/poi_custom.png'
                    }),
            ];
            map.entities.push(pins);
            Events.addHandler(pins[0], 'dragend', function () {
                var pin_location = pins[0].getLocation();
                $("#Latitude").val(pin_location.latitude);
                $("#Longitude").val(pin_location.longitude);
                Microsoft.Maps.loadModule('Microsoft.Maps.Search', function () {
                    var searchManager = new Microsoft.Maps.Search.SearchManager(map);
                    var reverseGeocodeRequestOptions = {
                        location: new Microsoft.Maps.Location(pin_location.latitude, pin_location.longitude),
                        callback: function (answer, userData) {
                            //map.setView({ bounds: answer.bestView });
                            $("#Alamat").val(answer.address.formattedAddress);
                        }
                    };
                    searchManager.reverseGeocode(reverseGeocodeRequestOptions);
                });
            });
        }
    </script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PointOfInterest/Views/Rumah/Index.cshtml
@model IEnumerable<PointOfInterest.Models.Rumah>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div id="myMap" style="position:relative; height:400px;"></div>
    </div>
</div>
<button type="button" onclick="location.href='@Url.Action("Create","Rumah")'" class="btn btn-success">
    <span class="glyphicon glyphicon-plus-sign">Create</span>
</button>
<hr />
<table id="Rumah" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alamat)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Alamat)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Rute" asp-route-id="@item.Id">Cari Rute</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#Rumah').DataTable();
        });
        function LoadMap() {
            map = new Microsoft.Maps.Map('#myMap', {
                credentials: KeyAPI,
            });
            map.setView({
                mapTypeId: Microsoft.Maps.MapTypeId.road,
                center: new Microsoft.Maps.Location(-6.914744, 107.609810),
                zoom: 13
            });
            LoadLoc();
        }
        function LoadLoc() {
            var url = "/Rumah/GetLocations";
            $.getJSON(url, null, function (data) {
                var pins = [];

                $.each(data, function (index, LocationData) {
                    var pushpin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location(
                        LocationData.latitude,
                        LocationData.longitude), { title: LocationData.name, icon: 'https://www.bingmapsportal.com/Content/images/poi_custom.png' });
                    pins.push(pushpin);
                });
                map.entities.push(pins);
                map.setView({
                    zoom: 13, center: new Microsoft.Maps.Location(-6.914744, 107.609810)
                });
            });
        }
    </script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
}

PointOfInterest/Views/Rumah/Rute.cshtml
@model PointOfInterest.Models.Rumah

@{
    ViewData["Title"] = "Rute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rute</h2>

<div>
    <h4>Rumah</h4>
    <hr />
    <input asp-for="Longitude" type="hidden" class="form-control" readonly="readonly" />
    <input asp-for="Latitude" type="hidden" class="form-control" readonly="readonly" />
    <input asp-for="Nama" type="hidden" class="form-control" readonly="readonly" />
    <input asp-for="Id" type="hidden" class="form-control" readonly="readonly" />
</div>
<div class="row">
    <div class="col-lg-8">
        <div id="myMap" style="position:relative; height:600px;"></div>
        <div class="form-group">
            <label class="control-label">Jarak Bedasarkan "Haversine" :</label>
            <input id="Jarak" class="form-control" readonly="readonly"/>
        </div>
    </div>
    <div class="col-lg-4">
        <div id='printoutPanel'></div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    <script type='text/javascript'>
        var lat = $("#Latitude").val();
        var long = $("#Longitude").val();
        var nama = $("#Nama").val();
        function LoadMap() {
            map = new Microsoft.Maps.Map('#myMap', {
                credentials: KeyAPI,
            });
            navigator.geolocation.getCurrentPosition(function (position) {
                $("#MyLatitude").val(position.coords.latitude);
                $("#MyLongitude").val(position.coords.longitude);
                CariRute(lat, long, position.coords.latitude, position.coords.longitude);
            });
            map.setView({
                mapTypeId: Microsoft.Maps.MapTypeId.road,
                center: new Microsoft.Maps.Location(-6.914744, 107.609810),
                zoom: 13
            });
           
        }

        function CariRute(lat, Long, my_lat, my_long) {
            var id = $("#Id").val();
            var url = "/Rumah/HitungJarak/" + id + "/" + my_lat + "/" + my_long;
            $.getJSON(url, function (data) {
                //data is the JSON string
                $("#Jarak").val(data);
            });
            Microsoft.Maps.loadModule('Microsoft.Maps.Directions', function () {
                var directionsManager = new Microsoft.Maps.Directions.DirectionsManager(map);
                directionsManager.setRequestOptions({ routeMode: Microsoft.Maps.Directions.RouteMode.driving });
                var waypoint1 = new Microsoft.Maps.Directions.Waypoint({ address: nama, location: new Microsoft.Maps.Location(lat, long) });
                var waypoint2 = new Microsoft.Maps.Directions.Waypoint({ address: 'My Location', location: new Microsoft.Maps.Location(my_lat, my_long) });
                directionsManager.addWaypoint(waypoint2);
                directionsManager.addWaypoint(waypoint1);
                directionsManager.setRenderOptions({ itineraryContainer: document.getElementById('printoutPanel') });
                directionsManager.calculateDirections();
            });
        }
    </script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}